---
- name: Install Ruby packeges
  hosts: all
  become: true
  vars:
    ruby_packages:
      - ruby-full
      - ruby-bundler
      - build-essential
  
  tasks:
  - name: Install ruby and rubygems and required packages
    apt:
      name: "{{ ruby_packages }}"
      state: present
      